var arrLang = {
    "fan": {
        "Home": "首頁",
        "Buy": "購買",
        "Title": "糖果派",
        "Ffp": "玩家盛宴",
        "Pcontract": "參與合約",
        "WantUpdate": "我要升級",
        "Invitefriends": "邀請好友",
        "Myincome": "我的收益",
        "Ruledescription": "規則說明",
        "Seemore": "查看更多",
        "Statisticaldata": "統計數據",
        "Incinerationrate": "門票焚毀倍率",
        "Burnedtickets": "已焚毀門票",
        "Currentlevel": "我的當前級別",
        "Directpush": "我的直推",
        "Fiveteam": "我團隊的五級玩家",
        "Nineteam": "我團隊的九級玩家",
        "Totalnumber": "我的團隊總人數",
        "Gradelevel": "我的級差級別",
        "Footer": "©2019 Team 糖果派 版權所有",
        "Purchase": "0.1ETH起購，兌換比例",
        "Pleasequantity": "請輸入數量",
        "Send": "發送",
        "Registeredreferee": "註冊推薦人",
        "Contactperson": "我的接點人",
        "Amountinput": "ETH金額輸入",
        "RequiredT19": "所需T19",
        "Upgrade": "升級",
        "Invite": "邀請",
        "Myinviter": "我的邀請人",
        "Mydirectpushes": "我的直推人數",
        "Invitationlink": "我的邀請鏈接",
        "Copyinvitationlink": "複製我的邀請鏈接",
        "Income": "收益",
        "Numbercoins": "平台幣數量",
        "Pendingincome": "待領取收益",
        "Settlementrevenue": "已結算收益",
        "NumberETH": "ETH數量",
        "Incometype": "收益類型",
        "Incometime": "收益時間",
        "Needtickets": "需支付門票",
        "Receive": "領取",
        "Settled": "已結算",
        "Level": "級差",
        "Totalsettled": "已結算ETH總數量：",
    },
    "en": {
        "Home": "Home",
        "Buy": "Buy",
        "Title": "Candy pie",
        "Ffp": "The player feast",
        "Pcontract": "Participation contract",
        "WantUpdate": "I want to upgrade",
        "Invitefriends": "Invite friends",
        "Myincome": "My income",
        "Ruledescription": "Rules Description",
        "Seemore": "View more",
        "Statisticaldata": "Statistics",
        "Incinerationrate": "Ticket burnout rate",
        "Burnedtickets": "The tickets have been burned",
        "Currentlevel": "My current level",
        "Directpush": "My direct push",
        "Fiveteam": "My team's five players",
        "Nineteam": "The nine players of my team",
        "Totalnumber": "The total number of my team",
        "Gradelevel": "My grade level",
        "Footer": "©2019 Team Candy Pie Copyright",
        "Purchase": "0.1ETH purchase, exchange ratio",
        "Pleasequantity": "Please enter the quantity",
        "Send": "Send",
        "Registeredreferee": "Registered referee",
        "Contactperson": "My contact person",
        "Amountinput": "ETH amount input",
        "RequiredT19": "Required T19",
        "Upgrade": "upgrade",
        "Invite": "Invitation",
        "Myinviter": "My inviter",
        "Mydirectpushes": "My direct pushes",
        "Invitationlink": "My invitation link",
        "Copyinvitationlink": "Copy my invitation link",
        "Income": "Revenue",
        "Numbercoins": "number of platform coins",
        "Pendingincome": "Pending income",
        "Settlementrevenue": "settled revenue",
        "NumberETH": "ETH Number",
        "Incometype": "type",
        "Incometime": "time",
        "Needtickets": "Need tickets",
        "Receive": "Receive",
        "Settled": "Closed",
        "Level": "Level difference",
        "Totalsettled": "Total number of settled ETH:",
    },
    "kor": {
        "Home": "첫 페이지",
        "Buy": "구매",
        "Title": "캔디 파이",
        "Ffp": "플레이어 잔치",
        "Pcontract": "참여 계약",
        "WantUpdate": "업그레이드하고 싶습니다",
        "Invitefriends": "친구 초대",
        "Myincome": "내 수입",
        "Ruledescription": "규칙 설명",
        "Seemore": "더보기",
        "Statisticaldata": "통계",
        "Incinerationrate": "티켓 소각 속도",
        "Burnedtickets": "구운 티켓",
        "Currentlevel": "내 현재 레벨",
        "Directpush": "내 직접 추진",
        "Fiveteam": "우리 팀의 다섯 선수",
        "Nineteam": "우리 팀의 9 명",
        "Totalnumber": "우리 팀의 총수",
        "Gradelevel": "내 학년",
        "Footer": "©2019 Team 사탕 파이 저작권",
        "Purchase": "0.1ETH 구매, 교환 비율",
        "Pleasequantity": "수량을 입력하십시오",
        "Send": "보내기",
        "Registeredreferee": "등록 된 심판",
        "Contactperson": "연락 담당자",
        "Amountinput": "ETH 금액 입력",
        "RequiredT19": "필수 T19",
        "Upgrade": "업그레이드",
        "Invite": "초대",
        "Myinviter": "내 초대 자",
        "Mydirectpushes": "내 직접 추진",
        "Invitationlink": "초대 링크",
        "Copyinvitationlink": "초대 링크 복사",
        "Income": "소득",
        "Numbercoins": "플랫폼 코인 수",
        "Pendingincome": "대기중인 소득",
        "Settlementrevenue": "정산 수익",
        "NumberETH": "ETH 수",
        "Incometype": "소득 유형",
        "Incometime": "수입 시간",
        "Needtickets": "티켓",
        "Receive": "받기",
        "Settled": "정착",
        "Level": "레벨 차이",
        "Totalsettled": "정산 된 총 ETH 수 :",
    },
    "jp": {
        "Home": "ホーム",
        "Buy": "購入する",
        "Title": "キャンディーパイ",
        "Ffp": "プレイヤーのごちそう",
        "Pcontract": "参加契約",
        "WantUpdate": "アップグレードしたい",
        "Invitefriends": "友達を招待する",
        "Myincome": "私の収入",
        "Ruledescription": "ルールの説明",
        "Seemore": "もっと見る",
        "Statisticaldata": "統計",
        "Incinerationrate": "チケット焼却率",
        "Burnedtickets": "燃えたチケット",
        "Currentlevel": "私の現在のレベル",
        "Directpush": "私の直接プッシュ",
        "Fiveteam": "私のチームの5人のプレーヤー",
        "Nineteam": "私のチームの9人のプレーヤー",
        "Totalnumber": "私のチームの総数",
        "Gradelevel": "私の学年",
        "Footer": "©2019 Team Candy Party 著作権",
        "Purchase": "0.1ETH購入、交換比率",
        "Pleasequantity": "数量を入力してください",
        "Send": "送る",
        "Registeredreferee": "登録審判",
        "Contactperson": "私の連絡先",
        "Amountinput": "ETH量の入力",
        "RequiredT19": "必要なT19",
        "Upgrade": "アップグレード",
        "Invite": "招待状",
        "Myinviter": "私の招待者",
        "Mydirectpushes": "私の直接プッシュ",
        "Invitationlink": "私の招待リンク",
        "Copyinvitationlink": "招待リンクをコピー",
        "Income": "収入",
        "Numbercoins": "プラットフォームコインの数",
        "Pendingincome": "保留中の収入",
        "Settlementrevenue": "決済収益",
        "NumberETH": "ETHの数",
        "Incometype": "タイプ",
        "Incometime": "時間",
        "Needtickets": "チケット",
        "Receive": "受け取る",
        "Settled": "落ち着いた",
        "Level": "レベル差",
        "Totalsettled": "決済済みETHの総数：",
    }
};